// Decompiled with JetBrains decompiler
// Type: UnitIconInfoExtension
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 84692B6C-DF14-44E0-9A18-AFF35C631E79
// Assembly location: B:\workspace\PotK Unit Database\Assembly Decompile\Assembly-CSharp.dll

using MasterDataTable;
using System;
using System.Collections.Generic;
using UniLinq;

#nullable disable
public static class UnitIconInfoExtension
{
  private static bool battleFirst;
  private static bool towerEntry;

  public static IEnumerable<UnitIconInfo> SortBy(
    this IEnumerable<UnitIconInfo> self,
    UnitSortAndFilter.SORT_TYPES type,
    SortAndFilter.SORT_TYPE_ORDER_BUY order,
    bool isBattleFirst,
    bool isTowerEntry)
  {
    UnitIconInfo unitIconInfo1 = (UnitIconInfo) null;
    List<UnitIconInfo> unitIconInfoList1 = new List<UnitIconInfo>();
    List<UnitIconInfo> unitIconInfoList2 = new List<UnitIconInfo>();
    UnitIconInfoExtension.battleFirst = isBattleFirst;
    UnitIconInfoExtension.towerEntry = isTowerEntry;
    foreach (UnitIconInfo unitIconInfo2 in self)
    {
      if (unitIconInfo2.removeButton)
        unitIconInfo1 = unitIconInfo2;
      else
        unitIconInfoList1.Add(unitIconInfo2);
    }
    switch (type)
    {
      case UnitSortAndFilter.SORT_TYPES.None:
        if (unitIconInfo1 != null)
          unitIconInfoList2.Insert(0, unitIconInfo1);
        return (IEnumerable<UnitIconInfo>) unitIconInfoList2;
      case UnitSortAndFilter.SORT_TYPES.BranchOfAnArmy:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.kind_GearKind)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.kind_GearKind)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Attribute:
        unitIconInfoList1.Sort((IComparer<UnitIconInfo>) new UnitIconInfoExtension.ElementComparer());
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, CommonElement>((Func<UnitIconInfo, CommonElement>) (ui => ui.playerUnit.GetElement())).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, CommonElement>((Func<UnitIconInfo, CommonElement>) (ui => ui.playerUnit.GetElement())).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Level:
      case UnitSortAndFilter.SORT_TYPES.MaxLevel:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Rarity:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.rarity.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.rarity.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Cost:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.cost)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.cost)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.FightingPower:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.combat)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.combat)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.PhysicalAttack:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.PhysicalAttack)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.PhysicalAttack)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.MagicAttack:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.MagicAttack)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.MagicAttack)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Defence:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.PhysicalDefense)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.PhysicalDefense)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.MagicDefence:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.MagicDefense)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.MagicDefense)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Hit:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Hit)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Hit)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Critical:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Critical)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Critical)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Avoid:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Evasion)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Evasion)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Speed:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Agility)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Agility)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Dexterity:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Dexterity)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Dexterity)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Luck:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Luck)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Luck)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.WeaponProficiency:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.weaponProficiency().ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.kind_GearKind)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.weaponProficiency().ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.kind_GearKind)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.ArmorProficiency:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.shildProficiency().ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.shildProficiency().ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.GetOrder:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, DateTime>((Func<UnitIconInfo, DateTime>) (ui => ui.playerUnit.created_at)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, DateTime>((Func<UnitIconInfo, DateTime>) (ui => ui.playerUnit.created_at)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.HP:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Hp)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.nonbattleParameter.Hp)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Breakthrough:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.breakthrough_count)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.breakthrough_count)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.UnityValue:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.unityTotal)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.unityTotal)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.TrustRate:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.unit.trust_target_flag)).ThenBy<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.trust_rate)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.unit.trust_target_flag)).ThenByDescending<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.trust_rate)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.AverageRisingValue:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.GetUnitAverageRisingValue())).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.GetUnitAverageRisingValue())).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.UnitName:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.name)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.name)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.Illustrator:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.unit.illustrator_name == string.Empty || ui.unit.illustrator_name == "")).ThenByDescending<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.illustrator_name)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.unit.illustrator_name == string.Empty || ui.unit.illustrator_name == "")).ThenBy<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.illustrator_name)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.VoiceActor:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.cv_name)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, string>((Func<UnitIconInfo, string>) (ui => ui.unit.cv_name)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.HistoryGroupNumber:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.history_group_number != 0 ? ui.unit.history_group_number : -1)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.history_group_number != 0 ? ui.unit.history_group_number : int.MaxValue)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.UnitID:
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? unitIconInfoList1.OrderByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ToList<UnitIconInfo>() : unitIconInfoList1.OrderBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      case UnitSortAndFilter.SORT_TYPES.PossessionNumber:
        Dictionary<int, int> dicPossessionNum = new Dictionary<int, int>();
        foreach (UnitIconInfo unitIconInfo3 in unitIconInfoList1)
        {
          int sameCharacterId = unitIconInfo3.unit.same_character_id;
          if (dicPossessionNum.ContainsKey(sameCharacterId))
            dicPossessionNum[sameCharacterId]++;
          else
            dicPossessionNum[sameCharacterId] = 1;
        }
        unitIconInfoList2 = order != SortAndFilter.SORT_TYPE_ORDER_BUY.ASCENDING ? UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => dicPossessionNum[ui.unit.same_character_id])).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.same_character_id)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.kind_GearKind)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenBy<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.unityTotal)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>() : UnitIconInfoExtension.GetOrderedList(unitIconInfoList1).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => dicPossessionNum[ui.unit.same_character_id])).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.same_character_id)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.kind_GearKind)).ThenBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.unit.character.ID)).ThenByDescending<UnitIconInfo, float>((Func<UnitIconInfo, float>) (ui => ui.playerUnit.unityTotal)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.unit.ID)).ThenByDescending<UnitIconInfo, int>((Func<UnitIconInfo, int>) (ui => ui.playerUnit.total_level)).ToList<UnitIconInfo>();
        goto case UnitSortAndFilter.SORT_TYPES.None;
      default:
        throw new Exception();
    }
  }

  private static IOrderedEnumerable<UnitIconInfo> GetOrderedList(List<UnitIconInfo> list)
  {
    IOrderedEnumerable<UnitIconInfo> orderedList = (IOrderedEnumerable<UnitIconInfo>) null;
    if (!UnitIconInfoExtension.battleFirst && !UnitIconInfoExtension.towerEntry)
      orderedList = list.OrderBy<UnitIconInfo, int>((Func<UnitIconInfo, int>) (a => 1));
    else if (UnitIconInfoExtension.battleFirst && UnitIconInfoExtension.towerEntry)
      orderedList = list.OrderByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.for_battle)).ThenByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.is_tower_entry));
    else if (UnitIconInfoExtension.battleFirst && !UnitIconInfoExtension.towerEntry)
      orderedList = list.OrderByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.for_battle));
    else if (!UnitIconInfoExtension.battleFirst && UnitIconInfoExtension.towerEntry)
      orderedList = list.OrderByDescending<UnitIconInfo, bool>((Func<UnitIconInfo, bool>) (ui => ui.is_tower_entry));
    return orderedList;
  }

  private class ElementComparer : IComparer<UnitIconInfo>
  {
    public int Compare(UnitIconInfo x, UnitIconInfo y)
    {
      if (x.playerUnit.GetElement() != CommonElement.none && y.playerUnit.GetElement() == CommonElement.none)
        return 1;
      return x.playerUnit.GetElement() == CommonElement.none && y.playerUnit.GetElement() != CommonElement.none ? -1 : 0;
    }
  }
}
